configuration/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('measurement-unit/', MeasurementUnitListView.as_view(), name='measurement-units'),
    path('measurement-unit/<int:pk>', MeasurementUnitDeleteView.as_view(), name='measurement-unit-delete'),
    path('service/', ServiceCreateListView.as_view(), name='services'),
    path('service/<int:pk>/', ServiceDeleteView.as_view(), name='service-delete'),
    path('tariff/', TariffListView.as_view(), name='tariffs'),
    path('tariff/create/', TariffCreateView.as_view(), name='tariff-create'),
    path('tariff/<int:pk>/', TariffDetailView.as_view(), name='tariff-detail'),
    path('tariff/update/<int:pk>/', TariffUpdateView.as_view(), name='tariff-update'),
    path('tariff/delete/<int:pk>/', tariff_delete, name='tariff-delete'),
    path('tariff-service/delete/<int:pk_tariff_service_to_delete>/', tariff_service_delete, name='tariff-service-delete'),
    path('roles/', RolesListUpdate.as_view(), name='roles'),
    path('user/', UserListView.as_view(), name='users'),
    path('user/create/', UserCreateView.as_view(), name='user-create'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user-detail'),
    path('user/update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('user/delete/<int:pk>', delete_user, name='user-delete'),
    path('requisites/', PaymentRequisitesCreateView.as_view(), name='requisites'),
    path('article-payment/', ArticlePaymentListView.as_view(), name='articles-payment'),
    path('article-payment/create/', ArticlePaymentCreateView.as_view(), name='article-payment-create'),
    path('article-payment/update/<int:pk>/', ArticlePaymentUpdateView.as_view(), name='article-payment-update'),
    path('article-payment/delete/<int:pk>/', delete_article, name='delete-article'),
    path('cabinet/login/', UserLoginView.as_view(), name='user-login'),
    path('cabinet/logout/', UserLogoutView.as_view(), name='user-logout'),
    path('admin/login/', ManagementLoginView.as_view(), name='user-staff-login'),
    path('admin/logout/', UserManagementLogoutView.as_view(), name='user-staff-logout'),
    path('user/registration/', UserRegistrationView.as_view(), name='user-registration'),
    path('user/activation/<str:uidb64>/<str:token>/', UserActivation.as_view(), name='user-activation')
]

front_side/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', MainPageDetailView.as_view(), name='main-page'),
    path('about-us/', AboutUsPageDetailView.as_view(), name='about-us-page'),
    path('service/', ServiceFrontPageDetailView.as_view(), name='service-page'),
    path('contact/', ContactPageDetailView.as_view(), name='contact-page')
]

my_house_24/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from my_house_24 import settings
from .views import PageNotFoundView, InternalServerError

from site_management.sitemaps import *


sitemaps = {
    'main_page': MainPageSitemap,
    'about_us': AboutUpsSitemap,
    'service': ServiceSitemap,
    'contact': ContactSitemap,
}

handler404 = PageNotFoundView.as_view()
handler505 = InternalServerError.as_view()

urlpatterns = [
    path('', include('front_side.urls')),
    path('administrator-panel/', include('administrator_panel.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('configuration/', include('configuration.urls')),
    path('site-management/', include('site_management.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

configuration/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import MinValueValidator
from django.urls import reverse

from phonenumber_field.modelfields import PhoneNumberField


class Role(models.Model):
    class RoleChoices(models.TextChoices):
        director = ('director', 'Директор')
        user = ('user', 'Користувач')
        manager = ('manager', 'Менеджер')
        accountant = ('accountant', 'Бухгалтер')
        electrician = ('electrician', 'Електрик')
        plumber = ('plumber', 'Сантехнік')
        owner = ('owner', 'Власник')

    role = models.CharField(max_length=40, choices=RoleChoices.choices, default='user')

    statistic_access = models.BooleanField(default=False)
    checkout_access = models.BooleanField(default=False)
    receipt_access = models.BooleanField(default=False)
    bill_access = models.BooleanField(default=False)
    flat_access = models.BooleanField(default=False)
    owner_access = models.BooleanField(default=False)
    building_access = models.BooleanField(default=False)
    message_access = models.BooleanField(default=False)
    master_apply_access = models.BooleanField(default=False)
    counter_access = models.BooleanField(default=False)
    site_management_access = models.BooleanField(default=False)
    service_access = models.BooleanField(default=False)
    tariff_access = models.BooleanField(default=False)
    role_access = models.BooleanField(default=False)
    user_access = models.BooleanField(default=False)
    payment_requisite_access = models.BooleanField(default=False)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            password=password,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        user = self.create_user(
            email,
            password=password,
            **extra_fields
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='Email', unique=True)
    name = models.CharField(max_length=200, verbose_name="Ім'я")
    surname = models.CharField(max_length=200, verbose_name='Прізвище')
    birthday = models.DateField(verbose_name='Дата народження', blank=True, null=True)
    logo = models.ImageField(upload_to='users/logos/', verbose_name='Лого', blank=True, null=True)
    father = models.CharField(max_length=200, verbose_name='По батькові', blank=True, null=True)
    phone = PhoneNumberField(verbose_name='Номер телефону', blank=True, null=True)
    viber = models.CharField(max_length=200, verbose_name='Viber', blank=True, null=True)
    owner_id = models.CharField(max_length=55, verbose_name='ID', blank=True, null=True)
    telegram = models.CharField(max_length=200, verbose_name='Telegram', blank=True, null=True)

    class StatusChoices(models.TextChoices):
        new = ('new', 'Новий')
        active = ('active', 'Активний')
        disconnected = ('disconnected', 'Відключений')

    status = models.CharField(max_length=20, choices=StatusChoices.choices, default='new', verbose_name='Статус')
    notes = models.TextField(verbose_name='Нотатки', blank=True, null=True)
    password = models.CharField(max_length=200, verbose_name='Пароль')
    role = models.ForeignKey(Role, on_delete=models.PROTECT, verbose_name='Роль')
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_absolute_url(self):
        if self.role.role != 'owner':
            return reverse('user-detail', kwargs={'pk': self.id})
        return reverse('owner-detail', kwargs={'owner_pk': self.id})


class MeasurementUnit(models.Model):
    name = models.CharField(max_length=200, verbose_name='Од. вим.')
    is_used = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('measurement-units')


class Service(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назва послуги')
    measurement_unit = models.ForeignKey(MeasurementUnit, on_delete=models.PROTECT)
    show_in_counters = models.BooleanField(default=True, verbose_name='Показувати в рахунок')
    is_used = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('services')


class Tariff(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назва тарифу')
    description = models.TextField(verbose_name='Опис тарифу')
    service_tariff = models.ManyToManyField(Service, through='TariffService', through_fields=('tariff', 'service'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редагування')

    def get_absolute_url(self):
        return reverse('tariff-detail', kwargs={'pk': self.id})


class TariffService(models.Model):
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name='Послуга')
    price = models.FloatField(verbose_name='Ціна', validators=[MinValueValidator(0)])
    currency = models.CharField(max_length=55, verbose_name='Валюта', default='грн')

    def delete(self, using=None, keep_parents=False):
        if not self.service.tariffservice_set.all().exists() \
                or (self.service.tariffservice_set.all().count() == 1 and self.service.tariffservice_set.all()[0].pk == self.pk):
            self.service.is_used = False
            self.service.save()
        return super(TariffService, self).delete(using, keep_parents)


class ArticlePayment(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назва')

    class TypeChoices(models.TextChoices):
        income = ('income', 'Прихід')
        outcome = ('outcome', 'Розхід')

    type = models.CharField(max_length=10, choices=TypeChoices.choices, verbose_name='Прихід/Розхід')

    def get_absolute_url(self):
        return reverse('articles-payment')


class PaymentRequisite(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назва компанії')
    information = models.TextField(verbose_name='Інформація')

    def get_absolute_url(self):
        return reverse('requisites')

configuration/forms.py
from django.forms import modelformset_factory, ModelForm, CharField, ModelChoiceField, FloatField, BooleanField
from django.forms.widgets import TextInput, CheckboxInput

from .models import *


def measurement_unit_formset(has_queryset):
    formset = modelformset_factory(MeasurementUnit,
                                   form=MeasurementUnitForm,
                                   extra=(0 if has_queryset else 1))
    return formset


def service_formset(has_queryset):
    formset = modelformset_factory(Service,
                                   form=ServiceForm,
                                   extra=(0 if has_queryset else 1))
    return formset


class MeasurementUnitForm(ModelForm):
    name = CharField(required=False)

    class Meta:
        model = MeasurementUnit
        exclude = ('is_used',)

    def clean(self, *args, **kwargs):
        cleaned_data = super(MeasurementUnitForm, self).clean()
        self._errors = {}

        return cleaned_data


class ServiceForm(ModelForm):
    name = CharField(required=False)
    measurement_unit = ModelChoiceField(required=False, queryset=MeasurementUnit.objects.all())

    class Meta:
        model = Service
        exclude = ('is_used',)

    def clean(self, *args, **kwargs):
        cleaned_data = super(ServiceForm, self).clean()
        self._errors = {}

        return cleaned_data


class TariffForm(ModelForm):

    class Meta:
        model = Tariff
        exclude = ('currency', 'service_tariff')

    def clean(self):
        cleaned_data = super(TariffForm, self).clean()
        self._errors = {}

        return cleaned_data


class TariffServiceForm(ModelForm):
    tariff = ModelChoiceField(required=False, queryset=Tariff.objects.all())
    service = ModelChoiceField(required=False, queryset=Service.objects.all())
    price = FloatField(required=False)

    class Meta:
        model = TariffService
        exclude = ('currency',)

    def clean(self):
        cleaned_data = super(TariffServiceForm, self).clean()
        self._errors = {}

        return cleaned_data


tariff_service_formset = modelformset_factory(TariffService,
                                              form=TariffServiceForm,
                                              extra=0)


role_formset = modelformset_factory(Role,
                                    exclude=('role',),
                                    extra=0)


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ('name', 'surname', 'phone', 'email', 'password', 'role', 'status')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()

        if self.instance:
            self._errors = {}

        return cleaned_data


class PaymentRequisitesForm(ModelForm):

    class Meta:
        model = PaymentRequisite
        fields = '__all__'


class ArticlePaymentForm(ModelForm):

    class Meta:
        model = ArticlePayment
        fields = '__all__'


class UserLoginForm(ModelForm):
    remember_me = BooleanField(widget=CheckboxInput(), required=False)

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        self._errors = {}
        if not cleaned_data.get('email'):
            self._errors['email'] = 'Поле не може бути пустим'

        if not cleaned_data.get('password'):
            self._errors['password'] = 'Поле не може бути пустим'

        print(self._errors)

        return cleaned_data

    def clean_email(self):
        if not self.cleaned_data.get('email'):
            self._errors['email'] = 'Поле не може бути пустим'
        return self.cleaned_data.get('email')


class UserSelfRegistrationForm(ModelForm):

    class Meta:
        model = User
        fields = ('surname', 'name', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def clean_email(self):
        obj = User.objects.filter(email=self.cleaned_data.get('email')).exclude(id=self.instance.id)
        if obj:
            self._errors['email'] = 'E-mail повинен бути унікальним'
        return self.cleaned_data.get('email')

configuration/templates/configuration/article-payment-create-update.html
{% extends 'main_page.html' %}
{% load static %}

{% block title %}
    <title>Статті</title>
{% endblock %}

{% block content_header %}
    <h1>{% if form.instance.id %}Редагування{% else %}Нова стаття{% endif %}</h1>
{% endblock %}

{% block main_content %}
    <div class="card">
        <div class="card-body">
            <form id="article-payment-form" method="post" {% if form.instance.id %}action="{% url 'article-payment-update' pk=form.instance.id %}" {% else %}action="{% url 'article-payment-create' %}"{% endif %}>
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-12 col-lg-7">
                    <div class="row">
                        <div class="form-group col-sm-12">
                            <label for="{{ form.name.auto_id }}">Назва</label>
                            <input type="text" class="form-control" id="{{ form.name.auto_id }}" name="{{ form.name.html_name }}" {% if form.instance %}value="{{ form.instance.name }}"{% endif %} onchange="fieldIsValid(this)">
                            <p id="{{ form.name.auto_id }}-errors" style="color: red;"></p>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 25px;">
                        <div class="form-group col-sm-12">
                            <label for="{{ form.type.auto_id }}">Прихід/розхід</label>
                            <select id="{{ form.type.auto_id }}" name="{{ form.type.html_name }}" class="form-select" onchange="fieldIsValid(this)">
                                <option value="income" {% if form.instance.type == 'income' %}selected{% endif %}>Прихід</option>
                                <option value="outcome" {% if form.instance.type == 'outcome' %}selected{% endif %}>Розхід</option>
                            </select>
                            <p id="{{ form.type.auto_id }}-errors" style="color: red"></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 text-right">
                    <button type="reset" class="btn btn-default" style="margin-right: 20px;">Відмінити</button>
                    <button type="submit" class="btn btn-success" onclick="formIsValid(event)">{% if form.instance.pk %}Зберегти{% else %}Створити{% endif %}</button>
                </div>
            </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    function formIsValid(e) {
        e.preventDefault();
        let isValidName = true;
        let isValidSelect = true;

        $(`#article-payment-form`).find(`input[id$='_name']`).each(function() {
            if (!fieldIsValid(this)) {
                isValidName = false;
            }
        });

        $(`#article-payment-form`).find(`select[id$='_type']`).each(function() {
            if (!fieldIsValid(this)) {
                isValidSelect = false;
            }
        });

        if (isValidName && isValidSelect) {
            $(`#article-payment-form`).submit();
            return true;
        }
        else {
            return false;
        }
    }
</script>
{% endblock %}

configuration/templates/configuration/article-payment-list.html
{% extends 'main_page.html' %}
{% load static %}

{% block title %}
    <title>Статті приходів/розходів</title>
{% endblock %}

{% block content_header %}
    <h1>Статті приходів/розходів</h1>
{% endblock %}

{% block main_content %}
    <div class="row" style="margin-bottom: 25px;">
        <div class="col-sm-12 text-right">
            <a class="btn btn-success" href="{% url 'article-payment-create' %}">Створити статтю</a>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <table class="table table-borderless table-hover">
                    <thead>
                        <tr>
                            <th>Назва</th>
                            <th style="color:#6084e0;">Прихід/розхід</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr role="button" data-href="{% url 'article-payment-update' pk=object.pk %}">
                            <td>{{ object.name }}</td>
                            <td style="color: {% if object.type == 'income' %}#20A202;{% else %}#BD2105;{% endif %}">{{ object.get_type_display }}</td>
                            <td class="text-right">
                                <div class="btn-group pull-right">
                                    <a class="btn btn-default btn-sm" title="Редагувати" href="{% url 'article-payment-update' pk=object.pk %}">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <button id="{{ object.pk }}" type="button" class="btn btn-default btn-sm delete-article" title="Видалити">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $('.delete-article').on('click', function (event) {
        event.stopPropagation();
        Swal.fire({
            title: 'Ви впевнені?',
            text: "Після видалення послугу неможливо буде повернути!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#A9A9A9',
            cancelButtonText: 'Скасувати',
            confirmButtonText: 'Видалити'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                            url: `delete/${$(this).attr('id')}`,
                            type: 'GET',
                            success: function (response) {
                                if (response['answer'] === 'success') {
                                    $(event.target).closest('tr').remove();
                                    Swal.fire({
                                        position: 'top-end',
                                        icon: 'success',
                                        title: 'Успішно видалено!',
                                        showConfirmButton: false,
                                        timer: 1200,
                                    })
                                }
                                else {
                                    Swal.fire({
                                        position: 'top-end',
                                        icon: 'error',
                                        title: 'Щось пішло не так!',
                                        showConfirmButton: false,
                                        timer: 1200
                                    });
                                }
                            }
                        })
                }
            })
    })
</script>
{% endblock %}

configuration/templates/configuration/role-list.html
{% extends 'main_page.html' %}
{% load static %}

{% block title %}
    <title>Ролі</title>
{% endblock %}

{% block content_header %}
    <h1>Ролі</h1>
{% endblock %}

{% block main_content %}
    <div class="card">
        <div class="card-body">
            <form id="roles-form" method="post" action="{% url 'roles' %}">
                {% csrf_token %}
                {{ formset.management_form }}
                <table class="table table-responsive table-bordered">
                    <thead>
                        <tr>
                            <th><b>Роль</b></th>
                            <th><b>Статистика</b></th>
                            <th><b>Каса</b></th>
                            <th><b>Квитанції на оплату</b></th>
                            <th><b>Особові рахунки</b></th>
                            <th><b>Квартири</b></th>
                            <th><b>Власники квартир</b></th>
                            <th><b>Дома</b></th>
                            <th><b>Повідомлення</b></th>
                            <th><b>Заявки виклика майстера</b></th>
                            <th><b>Рахунки</b></th>
                            <th><b>Управління сайтом</b></th>
                            <th><b>Послуги</b></th>
                            <th><b>Тарифи</b></th>
                            <th><b>Ролі</b></th>
                            <th><b>Користувачі</b></th>
                            <th><b>Платіжні реквізити</b></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for form in formset %}
                            {{ form.id }}
                            <tr class="text-center">
                                <td><b>{{ form.instance.get_role_display }}</b></td>
                                <td><input id="{{ form.statistic_access.auto_id }}" name="{{ form.statistic_access.html_name }}" type="checkbox" {% if form.instance.statistic_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.checkout_access.auto_id }}" name="{{ form.checkout_access.html_name }}" type="checkbox" {% if form.instance.checkout_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.receipt_access.auto_id }}" name="{{ form.receipt_access.html_name }}" type="checkbox" {% if form.instance.receipt_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.bill_access.auto_id }}" name="{{ form.bill_access.html_name }}" type="checkbox" {% if form.instance.bill_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.flat_access.auto_id }}" name="{{ form.flat_access.html_name }}" type="checkbox" {% if form.instance.flat_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.owner_access.auto_id }}" name="{{ form.owner_access.html_name }}" type="checkbox" {% if form.instance.owner_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.building_access.auto_id }}" name="{{ form.building_access.html_name }}" type="checkbox" {% if form.instance.building_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.message_access.auto_id }}" name="{{ form.message_access.html_name }}" type="checkbox" {% if form.instance.message_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.master_apply_access.auto_id }}" name="{{ form.master_apply_access.html_name }}" type="checkbox" {% if form.instance.master_apply_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.counter_access.auto_id }}" name="{{ form.counter_access.html_name }}" type="checkbox" {% if form.instance.counter_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.site_management_access.auto_id }}" name="{{ form.site_management_access.html_name }}" type="checkbox" {% if form.instance.site_management_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.service_access.auto_id }}" name="{{ form.service_access.html_name }}" type="checkbox" {% if form.instance.service_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.tariff_access.auto_id }}" name="{{ form.tariff_access.html_name }}" type="checkbox" {% if form.instance.tariff_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.role_access.auto_id }}" name="{{ form.role_access.html_name }}" type="checkbox" {% if form.instance.role_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.user_access.auto_id }}" name="{{ form.user_access.html_name }}" type="checkbox" {% if form.instance.user_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                                <td><input id="{{ form.payment_requisite_access.auto_id }}" name="{{ form.payment_requisite_access.html_name }}" type="checkbox" {% if form.instance.payment_requisite_access %}checked{% endif %} {% if form.instance.role == 'director' %}disabled{% endif %}></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <button type="reset" class="btn btn-default">Відміна</button>
                        <button type="submit" class="btn btn-success" style="margin-left: 20px;">Зберегти</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

configuration/templates/configuration/user-detail.html
{% extends 'main_page.html' %}
{% load static %}

{% block title %}
    <title>Користувачі</title>
{% endblock %}

{% block content_header %}
    <h1>Користувач</h1>
{% endblock %}

{% block main_content %}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12 text-right">
                    <a href="{% url 'user-update' pk=object.pk %}" class="btn btn-info">Редагувати користувача</a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th>Користувач</th>
                                <td>{{ object.name }} {{ object.surname }}</td>
                            </tr>
                            <tr>
                                <th>Роль</th>
                                <td>{{ object.role.get_role_display }}</td>
                            </tr>
                            <tr>
                                <th>Телефон</th>
                                <td>{{ object.phone }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ object.email }}</td>
                            </tr>
                            <tr>
                                <th>Статус</th>
                                <td>{% if object.status == 'new' %}<span class="badge badge-warning">{{ object.get_status_display }}</span>
                                {% elif object.status == 'active' %}<span class="badge badge-success">{{ object.get_status_display }}</span>
                                    {% else %}<span class="badge badge-danger">{{ object.get_status_display }}</span>{% endif %}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}