front_side/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', MainPageDetailView.as_view(), name='main-page'),
    path('about-us/', AboutUsPageDetailView.as_view(), name='about-us-page'),
    path('service/', ServiceFrontPageDetailView.as_view(), name='service-page'),
    path('contact/', ContactPageDetailView.as_view(), name='contact-page')
]

my_house_24/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from my_house_24 import settings
from .views import PageNotFoundView, InternalServerError

from site_management.sitemaps import *


sitemaps = {
    'main_page': MainPageSitemap,
    'about_us': AboutUpsSitemap,
    'service': ServiceSitemap,
    'contact': ContactSitemap,
}

handler404 = PageNotFoundView.as_view()
handler505 = InternalServerError.as_view()

urlpatterns = [
    path('', include('front_side.urls')),
    path('administrator-panel/', include('administrator_panel.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('configuration/', include('configuration.urls')),
    path('site-management/', include('site_management.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

additional/models.py
from django.db import models


class Seo(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    keywords = models.TextField(verbose_name='Keywords')


class Gallery(models.Model):
    name = models.CharField(max_length=200)


class Photo(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='gallery/')

front_side/models.py
from django.db import models

# Create your models here.

site_management/models.py
import os

from django.db import models
from django.urls import reverse

from phonenumber_field.modelfields import PhoneNumberField

from additional.models import Seo, Gallery, Photo


class MainPage(models.Model):
    seo = models.ForeignKey(Seo, on_delete=models.SET_NULL, blank=True, null=True)
    show_urls = models.BooleanField(default=True, verbose_name='Показувати посилання на додатки')
    slide_1 = models.ImageField(upload_to='main-page/slide-photos/', blank=True, null=True)
    slide_2 = models.ImageField(upload_to='main-page/slide-photos/', blank=True, null=True)
    slide_3 = models.ImageField(upload_to='main-page/slide-photos/', blank=True, null=True)
    title = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    short_text = models.TextField(verbose_name='Короткий текст', blank=True, null=True)
    block_header_1 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_1 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_1 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)
    block_header_2 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_2 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_2 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)
    block_header_3 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_3 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_3 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)
    block_header_4 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_4 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_4 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)
    block_header_5 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_5 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_5 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)
    block_header_6 = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    block_description_6 = models.TextField(verbose_name='Опис', blank=True, null=True)
    block_photo_6 = models.ImageField(upload_to='main-page/block-photos/', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('main-page')


class AboutUs(models.Model):
    gallery = models.ForeignKey(Gallery, related_name='gallery', on_delete=models.SET_NULL, blank=True, null=True)
    additional_gallery = models.ForeignKey(Gallery, related_name='additional_gallery', on_delete=models.SET_NULL, blank=True, null=True)
    seo = models.ForeignKey(Seo, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    director_photo = models.ImageField(upload_to='about-us/photo/director', blank=True, null=True)
    short_text = models.TextField(verbose_name='Короткий текст', blank=True, null=True)
    additional_title = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    additional_text = models.TextField(verbose_name='Короткий текст', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('about-us-page')


class ServiceFront(models.Model):
    seo = models.ForeignKey(Seo, on_delete=models.SET_NULL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('service-page')


class ServiceObjectFront(models.Model):
    service_front = models.ForeignKey(ServiceFront, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='service/photos/')
    title = models.CharField(max_length=200, verbose_name='Назва послуги')
    description = models.TextField()


class TariffPage(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    short_text = models.TextField(verbose_name='Короткий текст', blank=True, null=True)
    seo = models.ForeignKey(Seo, on_delete=models.SET_NULL, blank=True, null=True)


class TariffObjectFront(models.Model):
    tariff_page = models.ForeignKey(TariffPage, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='tariffs/photos/')
    title = models.CharField(max_length=200, verbose_name='Підпис')


class Contact(models.Model):
    seo = models.ForeignKey(Seo, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=200, verbose_name='Заголовок', blank=True, null=True)
    text = models.TextField(verbose_name='Короткий текст', blank=True, null=True)
    commercial_url = models.URLField(verbose_name='Посилання на комерційний сайт', blank=True, null=True)
    name_surname_father = models.CharField(max_length=200, verbose_name='ПІБ', blank=True, null=True)
    location = models.CharField(max_length=200, verbose_name='Локація', blank=True, null=True)
    address = models.CharField(max_length=200, verbose_name='Адреса', blank=True, null=True)
    phone = PhoneNumberField(verbose_name='Телефон', blank=True, null=True)
    email = models.EmailField(verbose_name='Email', blank=True, null=True)
    map_code = models.TextField(verbose_name='Код карти', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('contact-page')


class Document(models.Model):
    about_us = models.ForeignKey(AboutUs, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Назва документа')
    file = models.FileField(upload_to='about-us/files/')

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

front_side/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from site_management.models import *


class MainPageDetailView(DetailView):
    model = MainPage
    template_name = 'front_side/base_page_front.html'

    def get_object(self, queryset=None):
        return MainPage.objects.first()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.first()
        return context


class AboutUsPageDetailView(DetailView):
    model = AboutUs
    template_name = 'front_side/about-us.html'

    def get_object(self, queryset=None):
        return AboutUs.objects.prefetch_related('gallery__photo_set', 'additional_gallery__photo_set').first()


class ServiceFrontPageDetailView(DetailView):
    model = ServiceFront
    template_name = 'front_side/service.html'

    def get_object(self, queryset=None):
        return ServiceFront.objects.prefetch_related('serviceobjectfront_set').first()


class ContactPageDetailView(DetailView):
    model = Contact
    template_name = 'front_side/contact.html'

    def get_object(self, queryset=None):
        return Contact.objects.first()

front_side/templates/front_side/about-us.html
{% extends 'front_side/base_page_front.html' %}
{% load static %}

{% block header_list %}
<ul class="nav nav-pills">
    <li class="nav-item"><a href="{% url 'main-page' %}" class="nav-link">Головна</a></li>
    <li class="nav-item"><a href="{% url 'about-us-page' %}" class="nav-link active" aria-current="page">Про нас</a></li>
    <li class="nav-item"><a href="{% url 'service-page' %}" class="nav-link">Послуги</a></li>
    <li class="nav-item"><a href="https://google.com" class="nav-link">Умови покупки</a></li>
    <li class="nav-item"><a href="{% url 'contact-page' %}" class="nav-link">Контакти</a></li>
    <li class="nav-item"><a href="{% url 'user-login' %}" class="nav-link"><i class="fa fa-sign-in-alt"></i>  Вхід</a></li>
</ul>
{% endblock %}

{% block main_content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header">
                    <h4>{{ object.title }}</h4>
                </div>
                <img src="{{ object.director_photo.url }}" class="img-responsive float-right" style="width: 250px; height: 310px;">
                {{ object.short_text|safe }}
            </div>
        </div>
    </div>
    <div class="container" style="margin-top: 40px;">
        <div class="row">
            {% for obj in object.gallery.photo_set.all %}
                <div class="col-sm-12 col-md-6 col-lg-3">
                    <img class="img-thumbnail" src="{{ obj.photo.url }}" width="100%" style="height: 250px!important;">
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="container" >
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header">
                    <h4>{{ object.additional_title }}</h4>
                </div>
                {{ object.additional_text|safe }}
            </div>
        </div>
    </div>
    <div class="container" style="margin-top: 40px;">
        <div class="row">
            {% for obj in object.additional_gallery.photo_set.all %}
                <div class="col-sm-12 col-md-6 col-lg-3">
                    <img class="img-thumbnail" src="{{ obj.photo.url }}" width="100%" style="height: 250px!important;">
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

front_side/templates/front_side/contact.html
{% extends 'front_side/base_page_front.html' %}
{% load static %}

{% block header_list %}
<ul class="nav nav-pills">
    <li class="nav-item"><a href="{% url 'main-page' %}" class="nav-link">Головна</a></li>
    <li class="nav-item"><a href="{% url 'about-us-page' %}" class="nav-link">Про нас</a></li>
    <li class="nav-item"><a href="{% url 'service-page' %}" class="nav-link">Послуги</a></li>
    <li class="nav-item"><a href="https://google.com" class="nav-link">Умови покупки</a></li>
    <li class="nav-item"><a href="{% url 'contact-page' %}" class="nav-link active" aria-current="page">Контакти</a></li>
    <li class="nav-item"><a href="{% url 'user-login' %}" class="nav-link"><i class="fa fa-sign-in-alt"></i>  Вхід</a></li>
</ul>
{% endblock %}

{% block main_content %}
    {{ object.map_code|safe }}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-7 col-lg-8">
                <div class="page-header">
                    <h4>{{ object.title }}</h4>
                </div>
                <div class="box">
                    {{ object.text|safe }}
                </div>
            </div>
            <div class="col-sm-12 col-md-5 col-lg-4">
                <div class="page-header">
                    <h4>Контакти</h4>
                </div>
                <div class="box">
                    <p><i class="fa fa-user-circle"></i> {{ object.name_surname_father }}</p>
                    <p><i class="fa fa-compass"></i> {{ object.location }}</p>
                    <p><i class="fa fa-map-marker"></i> {{ object.address }}</p>
                    <p><i class="fa fa-phone"></i> <a href="tel:{{ object.phone }}">{{ object.phone }}</a></p>
                    <p><i class="fa fa-envelope"></i> <a href="mailto:{{ object.email }}">{{ object.email }}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front_side/templates/front_side/service.html
{% extends 'front_side/base_page_front.html' %}
{% load static %}

{% block header_list %}
<ul class="nav nav-pills">
    <li class="nav-item"><a href="{% url 'main-page' %}" class="nav-link">Головна</a></li>
    <li class="nav-item"><a href="{% url 'about-us-page' %}" class="nav-link">Про нас</a></li>
    <li class="nav-item"><a href="{% url 'service-page' %}" class="nav-link active" aria-current="page">Послуги</a></li>
    <li class="nav-item"><a href="https://google.com" class="nav-link">Умови покупки</a></li>
    <li class="nav-item"><a href="{% url 'contact-page' %}" class="nav-link">Контакти</a></li>
    <li class="nav-item"><a href="{% url 'user-login' %}" class="nav-link"><i class="fa fa-sign-in-alt"></i>  Вхід</a></li>
</ul>
{% endblock %}

{% block main_content %}
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h4>Наші послуги</h4>
            </div>
        </div>
        {% for obj in object.serviceobjectfront_set.all %}
            <div class="row" style="margin-bottom: 30px;">
                <div class="col-sm-12 col-lg-7">
                    <img class="img-responsive img-thumbnail" src="{{ obj.photo.url }}" style="width: 100%; height: 300px!important;">
                </div>
                <div class="col-sm-12 col-lg-5">
                    <div class="page-header" style="margin-top: 0">
                        <h4>{{ obj.title }}</h4>
                    </div>
                    {{ obj.description|safe }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}